cache:
  paths:
    - node_modules/
    - dist/
build:
    script:
        - npm install --registry=https://registry.npm.taobao.org
        - npm run build
        - rm -rf /opt/apache-tomcat-7.0.90/webapps/cqstcpops/*
        - cp -r dist/* /opt/apache-tomcat-7.0.90/webapps/cqstcpops
        - chown -R gitlab-runner /opt/apache-tomcat-7.0.90/webapps/cqstcpops/
